name: 'dbt_course'
version: '1.0.0'
profile: 'dbt_course'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  surrogate_key_treat_nulls_as_empty_strings: true

models:
  +post_hook: |
    
        CREATE SCHEMA IF NOT EXISTS logs;

        CREATE TABLE IF NOT EXISTS {{ target.database }}.logs.dbt_logs (
            event_date timestamp,
            event_name varchar(100),
            node_name varchar(256)
        );

        INSERT INTO {{ target.database }}.logs.dbt_logs
        (event_date, event_name, node_name)
        VALUES (
            CURRENT_TIMESTAMP, 'finish run model', '{{ model.name }}'
        )
       
  dbt_course:
    +materialized: view
    +meta: 
      owner: "dbt_project_yml@yahoo.com"
      year_owner: 2025
    staging:
      tags: staging
    intermediate:
      tags: intermediate



seeds:
  dbt_course:
    schema: seeds
