name: 'dbt_course'
version: '1.0.0'
profile: 'dbt_course'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"



models:
  dbt_course:
    +materialized: view
    +meta: 
      owner: "dbt_project_yml@yahoo.com"
      year_owner: 2025
    staging:
      tags: staging
    intermediate:
      tags: intermediate

seeds:
  dbt_course:
    schema: seeds
